RCPS-32 web-frontend-maintenance: Refactor Guest Violation Module
RoCS2024/osd-records-mgt-web pull request #22
Opened 2024-12-05 15:03 UTC by HaroldDinglasan

2024-12-05 16:00 UTC, zhairanicolepacheco requested changes

2024-12-05 16:00 UTC, zhairanicolepacheco commented on src/pages/Login.jsx
> +                        alert(response.data);
Remove unnecessary alert

2024-12-06 10:56 UTC, JustineDaveMagnaye approved these changes

2024-12-06 12:00 UTC, zhairanicolepacheco approved these changes

2024-12-06 12:12 UTC, esdi-00 commented on src/Constants.js
>  const prod = {
This file is getting ridiculously large and unmaintainable. In the next commit, just use one url each for dev and prod then just concatenate other parts of the api url when needed

2024-12-06 12:12 UTC, esdi-00 commented on src/component/AddViolationModal.jsx
> +                const token = sessionStorage.getItem('token');
why use a session storage? jwt is local storage based

2024-12-06 12:13 UTC, esdi-00 requested changes
address the local storage vs session storage issue

2024-12-06 13:37 UTC, PhilippaulDaganio approved these changes

2024-12-21 02:29 UTC, zhairanicolepacheco approved these changes

2024-12-21 02:33 UTC, closed without merging